"""Inject enriched factory data + richer popup into sources-of-truth.html."""
import re, pathlib

HTML = pathlib.Path(r'd:\graphics\Jero\MTIC\industrial_diagnostic_study\report\sources-of-truth.html')

# ── Enriched factory data ────────────────────────────────────────────────────
FACTORIES = [
  # ── Iron & Steel ──────────────────────────────────────────────────────────
  dict(name='Tembo Steels', chain='Iron & Steel', lat=0.3830, lng=32.9170,
       loc='Lugazi, Buikwe District',
       products='Steel billets, TMT/rebar, wire rod, structural sections, O₂/N₂ cylinders',
       capacity_installed='200,000 tpa rolling mill; 250,000 tpa DRI (Iganga plant)',
       capacity_utilised='Operational',
       employees='~1,600 direct; ~3,000 ecosystem',
       est=2001, ownership='Sanjay Awasthi (Chairman) — Indian-Ugandan private',
       exports='East Africa'),

  dict(name='Abyssinia Iron & Steel', chain='Iron & Steel', lat=0.4480, lng=33.2040,
       loc='Jinja',
       products='Steel billets, hot-rolled coil/rod, wire products, welding rods',
       capacity_installed='225,000 tpa billets',
       capacity_utilised='Operational since Oct 2024',
       employees='250 direct; ~1,200 indirect',
       est=2024, ownership='Abyssinia Group of Industries (AGI) — Jateen Patel family, Kenya/Ethiopia',
       exports='East Africa'),

  dict(name='Roofings Rolling Mills', chain='Iron & Steel', lat=0.3170, lng=32.7200,
       loc='Namanve Industrial Park, Kampala',
       products='Steel billets, TMT bars, wire rod, structural sections, galvanised products',
       capacity_installed='250,000 tpa (3 production units)',
       capacity_utilised='Operational',
       employees='~2,250 direct',
       est=2013, ownership='Roofings Group — Lalani family (Ugandan/South Asian); 10% Yodogawa Steel Works (Japan)',
       exports='East & Central Africa'),

  dict(name='Roofings Ltd', chain='Iron & Steel', lat=0.2490, lng=32.5480,
       loc='Lubowa, Wakiso District',
       products='Galvanised & pre-painted roofing sheets, steel pipes, polypipes, structural steel',
       capacity_installed='160,000 tpa cold-forming plant',
       capacity_utilised='Operational',
       employees='>2,000 group-wide',
       est=1994, ownership='Roofings Group — Sikander Lalani family (Ugandan/South Asian)',
       exports='East & Central Africa'),

  dict(name='Steel & Tube Industries', chain='Iron & Steel', lat=0.3210, lng=32.7240,
       loc='Namanve Industrial Park, Kampala',
       products='TMT rebars, wire rod, nails, fencing wire, angles, pipes',
       capacity_installed='>300,000 tpa installed',
       capacity_utilised='~43% utilisation',
       employees='>1,080',
       est=2006, ownership='Steel & Tube Industries Ltd (STIL) — Joseph Yiga (Chairman), Ugandan private',
       exports='East Africa'),

  dict(name='Uganda Baati', chain='Iron & Steel', lat=0.3080, lng=32.5890,
       loc='Kampala',
       products='Galvanised, Al-Zn coated and pre-painted roofing sheets, stone-coated tiles',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=1964, ownership='Safal Group (Aga Khan Fund for Economic Development / IPS) — Pan-African',
       exports='East Africa'),

  dict(name='Devki Steel Mill (under construction)', chain='Iron & Steel', lat=0.3190, lng=32.7160,
       loc='Namanve Industrial Park, Kampala',
       products='Integrated steel — billets, bars, sections (blast furnace route)',
       capacity_installed='1,000,000 tpa planned at full capacity',
       capacity_utilised='Under construction — groundbreaking Nov 2025',
       employees='15,000 projected at start-up',
       est=2025, ownership='Devki Group — Dr Narendra Raval family (Kenya); USD 500 m project',
       exports='East Africa (planned)'),

  dict(name='SINO Minerals — Iron Ore', chain='Iron & Steel', lat=-1.2540, lng=29.9880,
       loc='Kabale District',
       products='Iron ore, pig iron processing',
       capacity_installed='~30 m tonne ore reserve @ 58% Fe; USD 34 m plant',
       capacity_utilised='Partial / under development',
       employees='>1,000 projected',
       est=2011, ownership='Sino Minerals Investments Co. Ltd — Chinese nationals (Li Bin et al.)',
       exports='—'),

  dict(name='MM Integrated Steel Mills (MMI Steels)', chain='Iron & Steel', lat=0.4260, lng=33.2200,
       loc='Masese/Walukuba, Jinja',
       products='TMT bars, roofing sheets, wire rod, structural steel',
       capacity_installed='~50,000 tpa (Uganda plant); 350,000 tpa group aggregate',
       capacity_utilised='Operational',
       employees='—',
       est=2013, ownership='Motisun Group — Tanzania-based private conglomerate',
       exports='East Africa'),

  dict(name='Steel Rolling Mills Ltd (Alam Group)', chain='Iron & Steel', lat=0.4230, lng=33.2160,
       loc='Masese Road, Jinja',
       products='High-tensile steel profiles, sections, bars',
       capacity_installed='—', capacity_utilised='Operational',
       employees='~2,500 (peak; significant layoffs reported 2019–21)',
       est=1987, ownership='Alam Group of Companies — Uganda, South Asian-origin',
       exports='East Africa'),

  dict(name='Pramukh Steel Ltd', chain='Iron & Steel', lat=0.4180, lng=33.1830,
       loc='Njeru, Buikwe District',
       products='TMT/ribbed bars, round/square bars, binding wire',
       capacity_installed='>80,000 tpa',
       capacity_utilised='Operational',
       employees='—',
       est=2007, ownership='Indian-origin private; initial investment USD 5 m, grown to USD 20 m',
       exports='Kenya, Rwanda, DRC, Burundi, South Sudan'),

  dict(name='Yogi Steels Ltd', chain='Iron & Steel', lat=0.4160, lng=33.1810,
       loc='Njeru, Buikwe District',
       products='TMT bars, round/flat/angle bars, nails, binding wire',
       capacity_installed='>51,000 tpa',
       capacity_utilised='Operational',
       employees='—',
       est=2012, ownership='Alpesh Patel (Managing Director) — Indian-origin private',
       exports='Kenya, Rwanda, DRC, Burundi, South Sudan'),

  dict(name='MPower Steel Company Ltd', chain='Iron & Steel', lat=0.3420, lng=32.6950,
       loc='Kira Municipality / Namanve area',
       products='TMT steel bars (Thermax German technology)',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2020, ownership='MPower Group — interests across energy, steel and Africa/Asia',
       exports='—'),

  dict(name='Starfly Steel (Uganda) Co. Ltd', chain='Iron & Steel', lat=0.3500, lng=32.7100,
       loc='Seeta, Mukono District',
       products='Hot-rolled coil/plate, H-beam, channel, angle steel, welding rod',
       capacity_installed='Processing & distribution centre (not integrated mill)',
       capacity_utilised='665 export shipments recorded',
       employees='—',
       est=2020, ownership='Chinese-founded; CEO Joseph Kaggwe',
       exports='Regional'),

  dict(name='Elgon Steel Uganda Ltd (under construction)', chain='Iron & Steel', lat=1.0840, lng=34.1780,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Steel (product mix not yet announced)',
       capacity_installed='—', capacity_utilised='Under construction',
       employees='—',
       est=2024, ownership='Chinese investor — Sino-Uganda Mbale Industrial Park',
       exports='—'),

  dict(name='BM Investments Ltd', chain='Iron & Steel', lat=-0.6050, lng=30.6620,
       loc='Mbarara',
       products='Wire nails, fencing wire, transmission poles, timber products',
       capacity_installed='15,600 electrical poles p.a.; 250,000 fencing poles p.a.',
       capacity_utilised='Operational',
       employees='—',
       est=1984, ownership='Francis Mwebesa (Chairman) — Ugandan private',
       exports='—'),

  dict(name='CMIC Steel Plant', chain='Iron & Steel', lat=-0.6200, lng=30.6500,
       loc='Mbarara District',
       products='Iron and steel products',
       capacity_installed='USD 100 m integrated iron ore + steel plant (announced)',
       capacity_utilised='Partial / limited operations',
       employees='—',
       est=2012, ownership='CMIC — China Machine Building International Corporation (state-linked)',
       exports='—'),

  dict(name='Unisteel Investments Uganda Ltd', chain='Iron & Steel', lat=1.0770, lng=34.1720,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Steel bars and sections',
       capacity_installed='700,000 tpa',
       capacity_utilised='500 employees at commissioning; 3,000 projected',
       employees='500 (at launch 2024)',
       est=2024, ownership='Xu Shicun (Chinese investor) — USD 100 m investment',
       exports='East Africa (planned)'),

  dict(name='ZhongGang Metal R&D Manufacturing', chain='Iron & Steel', lat=1.0810, lng=34.1760,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Metal and steel R&D manufacturing products',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2019, ownership='Chinese investor — Sino-Uganda Mbale Industrial Park',
       exports='—'),

  dict(name='Tembo Steels — Iganga Plant', chain='Iron & Steel', lat=0.6091, lng=33.4685,
       loc='Iganga District',
       products='Sponge iron (DRI), structural steel sections',
       capacity_installed='DRI plant: 1,200 tpa (plant 1); 250 tpa (plant 2); Structure Mill: 200,000 tpa',
       capacity_utilised='Operational',
       employees='Part of Tembo group (~1,600 direct)',
       est=2022, ownership='Tembo Steels (U) Ltd — Sanjay Awasthi (Chairman)',
       exports='East Africa'),

  # ── Copper & Allied Metals ────────────────────────────────────────────────
  dict(name='Cable Corporation Ltd (Mehta Group)', chain='Copper & Allied Metals', lat=0.4440, lng=33.1960,
       loc='Jinja',
       products='Aluminium/copper conductors, armoured cables, domestic wires, control/submersible/welding cables',
       capacity_installed='—',
       capacity_utilised='~65% Uganda market share',
       employees='—',
       est=1968, ownership='Mehta Group — India/Uganda',
       exports='Kenya, Tanzania, Rwanda, South Sudan'),

  dict(name='East African Cables Uganda', chain='Copper & Allied Metals', lat=0.3170, lng=32.7120,
       loc='Namanve, Kampala',
       products='Power cables, overhead conductors, winding wire',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2005, ownership='East African Cables PLC — Kenya (NSE-listed)',
       exports='East Africa'),

  dict(name='Kilembe Copper Mine', chain='Copper & Allied Metals', lat=0.1300, lng=30.0380,
       loc='Kilembe, Kasese District',
       products='Copper ore, cobalt ore',
       capacity_installed='>6.5 m tonne copper ore reserve; 5.5 m tonne cobalt ore',
       capacity_utilised='Partial rehabilitation; dormant since 1980s',
       employees='4,000 projected when fully operational',
       est=1950, ownership='UNMC + Sarrai Group + Nile Fibre (PSA signed Mar 2025)',
       exports='Copper/cobalt concentrate for export'),

  dict(name='Orion Transformers & Electrics Ltd', chain='Copper & Allied Metals', lat=0.3200, lng=32.7290,
       loc='Namanve Industrial Park',
       products='Distribution transformers (100 kVA–2,500 kVA/33 kV), switchgear',
       capacity_installed='500,000 kVA p.a.; ~1,500 transformers p.a.',
       capacity_utilised='~USD 10 m output p.a.',
       employees='—',
       est=2015, ownership='Sino-Uganda JV — Shineng Group (China) + Ugandan partner',
       exports='East Africa'),

  dict(name='Steema Transformers & Electricals', chain='Copper & Allied Metals', lat=0.3230, lng=32.7310,
       loc='Namanve Industrial Park',
       products='Transformers (100 kVA–15 MVA), stabilisers, VCB panels',
       capacity_installed='—', capacity_utilised='Operational since Oct 2019',
       employees='—',
       est=2019, ownership='Arya Electronics (Gujarat, India) — Indian private',
       exports='East Africa'),

  dict(name='Total Cables (U) Ltd', chain='Copper & Allied Metals', lat=0.3240, lng=32.7150,
       loc='Namanve Industrial Park area',
       products='Copper wire, electric power cables, conductors (domestic and industrial)',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2018, ownership='Victoria Group (sister company of Yogi Steels Ltd)',
       exports='East Africa'),

  # ── Automotive ────────────────────────────────────────────────────────────
  dict(name='Kiira Motors Corporation (KMC)', chain='Automotive', lat=0.4480, lng=33.2100,
       loc='Kiira Vehicle Plant, Jinja',
       products='Electric buses (Kayoola EVS), low-emission diesel buses, electric trucks',
       capacity_installed='5,000 vehicles p.a. installed; 28 buses/day throughput',
       capacity_utilised='~39 buses assembled as of mid-2024; ramping up',
       employees='168 (growing to 600 at full ops)',
       est=2014, ownership='Government of Uganda — 100% state enterprise',
       exports='East Africa (planned)'),

  dict(name='Bus / Truck Body Fabricators', chain='Automotive', lat=0.3200, lng=32.5800,
       loc='Kampala / Jinja Industrial Area',
       products='Custom bus and truck body fabrication on imported chassis',
       capacity_installed='—', capacity_utilised='Active cluster',
       employees='—',
       est=0, ownership='Multiple SME fabricators — predominantly Ugandan private',
       exports='—'),

  dict(name='After-Market Parts Cluster (Ndeeba/Kisekka)', chain='Automotive', lat=0.3060, lng=32.5630,
       loc='Ndeeba / Kisekka Market, Kampala',
       products='Automotive spare parts, machined components, reconditioned parts',
       capacity_installed='—',
       capacity_utilised='Serves >2.3 m registered vehicles in Uganda',
       employees='—',
       est=0, ownership='Informal/SME cluster — Ugandan private traders and small manufacturers',
       exports='—'),

  dict(name='Zembo Electric Motorcycles', chain='Automotive', lat=0.3476, lng=32.6199,
       loc='Ntinda, Kampala',
       products='Electric motorcycles (e-boda bodas), Li-ion battery packs, battery swap services',
       capacity_installed='60,000 units p.a.',
       capacity_utilised='>2,000 motorcycles on road (2024)',
       employees='~360',
       est=2017, ownership='Bodawerk International Ltd — Daniel Dreher & team (European founders); PIDG-backed',
       exports='—'),

  dict(name='Gogo Electric', chain='Automotive', lat=0.3490, lng=32.6220,
       loc='Ntinda Kigowa Road, Kampala',
       products='Electric motorcycles, Li-ion battery packs, battery swap services',
       capacity_installed='60,000 units p.a.',
       capacity_utilised='>2,000 motorcycles on road; 66 swap stations (2024)',
       employees='>360 (40% women)',
       est=2020, ownership='Ben Lokeris Koriang & Jakob Hornbach (Ugandan/European co-founders); Africa Go Green Fund',
       exports='—'),

  dict(name='Spiro (under construction)', chain='Automotive', lat=0.3110, lng=32.5770,
       loc='Kampala',
       products='Electric motorcycles (assembly), battery swap infrastructure',
       capacity_installed='450 motorcycles/day',
       capacity_utilised='500 deployed in Uganda in one day (Jul 2025)',
       employees='—',
       est=2022, ownership='Equitane Group — Gagan Gupta (Dubai-based); 6 African countries',
       exports='Togo, Benin, Rwanda, Kenya, Nigeria'),

  dict(name='Hercules Automobile Manufacturing (under construction)', chain='Automotive', lat=1.0850, lng=34.1800,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Automobiles (product mix TBC)',
       capacity_installed='—', capacity_utilised='Under construction',
       employees='—',
       est=2024, ownership='Chinese investor — Sino-Uganda Mbale Industrial Park',
       exports='—'),

  dict(name='Uganda Batteries Ltd (UBL)', chain='Automotive', lat=0.3160, lng=32.6090,
       loc='Bugolobi, Kampala',
       products='Lead-acid automotive batteries, solar batteries',
       capacity_installed='—',
       capacity_utilised='Leading battery manufacturer in Uganda',
       employees='35–61',
       est=1967, ownership='Dr James Mulwana family (Ugandan); originally JV with Chloride UK; full Ugandan ownership since 1990',
       exports='East Africa'),

  # ── Textiles & Garments ───────────────────────────────────────────────────
  dict(name='Southern Range Nyanza (Nytil)', chain='Textiles & Garments', lat=0.4450, lng=33.1970,
       loc='Jinja',
       products='Woven fabric, T-shirts, bed sheets, pillow cases, quilts; spinning, weaving, dyeing',
       capacity_installed='8,000 kg spinning/24 h; 100,000 m weaving/24 h; 150,000 bales fabric p.a.',
       capacity_utilised='90% exported',
       employees='1,500',
       est=1954, ownership='Southern Range Nyanza Ltd — private (acquired from GoU 1996)',
       exports='135,000 bales p.a. to East Africa & beyond'),

  dict(name='Fine Spinners Ltd', chain='Textiles & Garments', lat=0.2990, lng=32.6330,
       loc='Luzira, Kampala',
       products='Cotton-based textiles, sustainable traceable garments',
       capacity_installed='—', capacity_utilised='~USD 50 m turnover',
       employees='~106 direct; ~18,000 incl. outgrowers',
       est=2014, ownership='Jaswinder Bedi (Director) — private',
       exports='—'),

  dict(name='Lira Spinning Facility', chain='Textiles & Garments', lat=2.2490, lng=32.9000,
       loc='Lira',
       products='Spun cotton yarn',
       capacity_installed='—',
       capacity_utilised='Dormant (mill vandalised; Chinese revamp stalled)',
       employees='~40 technicians + 200 casual (attempted restart)',
       est=1962, ownership='Jinda International Textile Corporation (Chinese); bought from GoU 2000',
       exports='—'),

  dict(name='Sunbelt Textiles Company Ltd', chain='Textiles & Garments', lat=0.4260, lng=33.2140,
       loc='Walukuba-Masese Road, Jinja',
       products='Woven fabrics, bedsheets, bed covers, pillow cases; weaving, dyeing, printing, sewing',
       capacity_installed='USD 18 m plant',
       capacity_utilised='Operational; ~400+ on-site workers',
       employees='~400',
       est=2012, ownership='Chinese management/ownership',
       exports='East Africa'),

  dict(name='Sigma Knitting Industries Ltd', chain='Textiles & Garments', lat=0.4270, lng=33.2020,
       loc='Jinja',
       products='Uniforms, socks, knitted garments',
       capacity_installed='—',
       capacity_utilised='One of most modern textile plants in East & Central Africa',
       employees='—',
       est=0, ownership='Anant Parmar (Managing Director)',
       exports='East Africa'),

  dict(name='Nice Textiles Uganda Ltd', chain='Textiles & Garments', lat=1.0800, lng=34.1740,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Textiles and garments',
       capacity_installed='—', capacity_utilised='Operational (commissioned 2024)',
       employees='—',
       est=2024, ownership='Chinese investor — Sino-Uganda Mbale Industrial Park',
       exports='—'),

  dict(name='Xinlong Textile & Garment Technology', chain='Textiles & Garments', lat=1.0760, lng=34.1710,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Textiles and garments',
       capacity_installed='—', capacity_utilised='Operational (commissioned 2024)',
       employees='—',
       est=2024, ownership='Chinese investor — Sino-Uganda Mbale Industrial Park',
       exports='—'),

  dict(name='Wan Way Textile & Garment Manufacturing', chain='Textiles & Garments', lat=1.0790, lng=34.1730,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Textiles and garments',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2019, ownership='Chinese investor — Sino-Uganda Mbale Industrial Park',
       exports='East Africa'),

  dict(name='Grace Textile International Investment', chain='Textiles & Garments', lat=1.0820, lng=34.1760,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Textiles, garments, foam',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2018, ownership='Chinese-owned; MoF Uganda tax incentives',
       exports='East Africa'),

  dict(name='Hang Da Textile Co. Ltd', chain='Textiles & Garments', lat=1.0830, lng=34.1790,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Textiles and garments',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2019, ownership='Chinese investor — Sino-Uganda Mbale Industrial Park',
       exports='—'),

  dict(name='Camry Clothes Ltd', chain='Textiles & Garments', lat=1.0750, lng=34.1700,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Garments / apparel',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2019, ownership='Chinese investor — Sino-Uganda Mbale Industrial Park',
       exports='East Africa'),

  dict(name='Leather Industries of Uganda (LIU)', chain='Textiles & Garments', lat=0.4150, lng=33.2060,
       loc='Fishermans Point, Jinja',
       products='Wet blue hides, crust leather, finished leather',
       capacity_installed='750 hides/day; ~200 containers wet blue p.a.',
       capacity_utilised='Operational',
       employees='>500',
       est=1995, ownership='Industrial Promotion Services (IPS / Aga Khan Development Network)',
       exports='Wet blue to Asia/Europe; finished leather to East Africa'),

  dict(name='Leather Works Limited', chain='Textiles & Garments', lat=0.4290, lng=33.2050,
       loc='Jinja',
       products='Vegetable-tanned leather, chrome washers for cotton ginneries',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=0, ownership='Private (details limited)',
       exports='—'),

  dict(name='Kawumu Tannery', chain='Textiles & Garments', lat=0.6760, lng=32.4320,
       loc='Kawumu village, Luweero District',
       products='Processed hides, finished leather, footwear (shoes)',
       capacity_installed='10 tonnes hides/day → 35,000 sq ft leather/day',
       capacity_utilised='Operational since Aug 2022',
       employees='1,200 projected',
       est=2022, ownership='Government of Uganda — UGX 12 bn investment',
       exports='—'),

  # ── Pharmaceuticals ───────────────────────────────────────────────────────
  dict(name='QCIL — Cipla Quality Chemical', chain='Pharmaceuticals', lat=0.3160, lng=32.7220,
       loc='Namanve Industrial Park, Kampala',
       products='ARVs, anti-malarials, hepatitis B, NCD medicines — tablets & capsules',
       capacity_installed='~1.2 billion pills/year',
       capacity_utilised='Approved in 31 African countries; UGX 267 bn revenue',
       employees='>500',
       est=2005, ownership='Cipla Ltd (India) + Quality Chemicals Ltd (Uganda, USE-listed)',
       exports='13 African countries; WHO-GMP prequalified'),

  dict(name='Kampala Pharmaceutical Industries (KPI)', chain='Pharmaceuticals', lat=0.3130, lng=32.5910,
       loc='Kampala',
       products='Essential medicines — tablets, capsules, liquid orals, dry syrup, sachets, veterinary',
       capacity_installed='—', capacity_utilised='Operational',
       employees='~300',
       est=1996, ownership='Industrial Promotion Services (IPS/Aga Khan) + Kopran Ltd (India)',
       exports='East Africa'),

  dict(name='Rene Industries', chain='Pharmaceuticals', lat=0.3110, lng=32.5840,
       loc='Kampala',
       products='Tablets, capsules, liquid orals, dry syrup, sachets, external preparations (120+ products)',
       capacity_installed='2.8 billion tablets/month',
       capacity_utilised='Operational',
       employees='~800',
       est=1996, ownership='Rishi Vadodaria family — Indian-origin, Ugandan',
       exports='East Africa'),

  dict(name='Abacus Pharma', chain='Pharmaceuticals', lat=0.3150, lng=32.5960,
       loc='Kampala',
       products='Parenteral drugs (IV solutions), pharmaceuticals',
       capacity_installed='11,000 m² parenteral plant — largest in East Africa',
       capacity_utilised='Supplies majority of regional IV demand',
       employees='>200 manufacturing; >1,200 group-wide',
       est=1995, ownership='Carlyle Group + Akayi Group',
       exports='Kenya, Tanzania, Rwanda, Burundi, Ethiopia'),

  dict(name='Surgipharm Uganda Ltd', chain='Pharmaceuticals', lat=0.3180, lng=32.5800,
       loc='Kampala',
       products='Pharmaceutical and diagnostic products (distribution and manufacturing)',
       capacity_installed='—', capacity_utilised='Operational',
       employees='~96',
       est=1997, ownership='Kishore Reddy (Operations Director) — private',
       exports='Rwanda'),

  dict(name='Pyramid Pharma Uganda', chain='Pharmaceuticals', lat=0.3100, lng=32.5870,
       loc='Kampala',
       products='Generic medicines, temperature-sensitive pharmaceutical logistics',
       capacity_installed='—',
       capacity_utilised='ISO 9001:2015 certified',
       employees='—',
       est=2012, ownership='Pyramid Pharma Ltd (Tanzania) — 7-country East Africa footprint',
       exports='East Africa'),

  dict(name='Mu Pharma Co. SMC Ltd', chain='Pharmaceuticals', lat=0.3300, lng=32.5730,
       loc='Bombo Road, Kampala',
       products='Pharmaceutical imports, exports and distribution (medical supplies)',
       capacity_installed='—',
       capacity_utilised='USD 14.6 m revenue',
       employees='51–200',
       est=2017, ownership='Private — Middle East/Asian supplier partnerships',
       exports='Sudan, South Sudan'),

  # ── Petrochemicals & Fertilizers ──────────────────────────────────────────
  dict(name='Kabaale Refinery (under construction)', chain='Petrochemicals & Fertilizers', lat=1.4200, lng=31.3500,
       loc='Kabaale, Hoima District',
       products='Crude oil refinery — petroleum fuels, petrochemicals, kerosene (planned)',
       capacity_installed='60,000 bpd',
       capacity_utilised='Under construction — target ops Q4 2029/Q1 2030',
       employees='—',
       est=2025, ownership='UNOC (GoU, 40%) + Alpha MBM Investments (UAE, 60%); USD 4 bn total',
       exports='Regional petroleum exports planned'),

  dict(name='Sukulu / Osukuru Phosphate Plant', chain='Petrochemicals & Fertilizers', lat=0.6950, lng=34.1520,
       loc='Tororo',
       products='Phosphate fertilizers (triple superphosphate), cement, lime',
       capacity_installed='50,000 tpa fertiliser (Phase 1); target 100,000 tpa',
       capacity_utilised='Partial / intermittent; resumed after 2021 shutdown',
       employees='—',
       est=2016, ownership='Guangzhou Dong Song Energy Co. Ltd (China) + Government of Uganda JV; USD 560–620 m',
       exports='East Africa'),

  dict(name='Vivo Energy — LPG Filling Plant Mbale', chain='Petrochemicals & Fertilizers', lat=1.0890, lng=34.1820,
       loc='Mbale City',
       products='LPG filling and storage, Shell Gas distribution',
       capacity_installed='—',
       capacity_utilised='Commissioned Jan 2026',
       employees='—',
       est=2026, ownership='Vivo Energy Uganda (licensed Shell operator; Vitol Group / Vivo Energy PLC)',
       exports='—'),

  dict(name='Vivo Energy / UNOC — Kabalega LPG Hub (under construction)', chain='Petrochemicals & Fertilizers', lat=1.4350, lng=31.3550,
       loc='Kabalega Industrial Park, Hoima',
       products='LPG storage, cylinder filling, handling infrastructure',
       capacity_installed='—',
       capacity_utilised='Under development — agreement signed Jul 2025',
       employees='—',
       est=2025, ownership='Vivo Energy Uganda + UNOC JV; part of USD 550 m clean-cooking commitment',
       exports='—'),

  dict(name='Kansai Plascon Uganda Ltd', chain='Petrochemicals & Fertilizers', lat=0.3280, lng=32.7190,
       loc='Namanve Industrial Park',
       products='Decorative, automotive and industrial paints and coatings',
       capacity_installed='USD 10 m plant',
       capacity_utilised='Operational',
       employees='—',
       est=2017, ownership='Kansai Plascon Africa Ltd — subsidiary of Kansai Paint Co. (Japan)',
       exports='East Africa'),

  dict(name='Sadolin / Crown Paints East Africa', chain='Petrochemicals & Fertilizers', lat=0.3310, lng=32.7210,
       loc='Namanve Industrial Park',
       products='Decorative paints (Sadolin brand); >50% Uganda market share',
       capacity_installed='UGX 10 bn plant investment',
       capacity_utilised='Operational',
       employees='200–250',
       est=1963, ownership='Crown Paints Kenya Ltd / AkzoNobel licensing; Kansai Plascon umbrella',
       exports='East Africa'),

  # ── Sugar & Confectionery ─────────────────────────────────────────────────
  dict(name='Kakira Sugar Works', chain='Sugar & Confectionery', lat=0.4170, lng=33.2850,
       loc='Kakira, Jinja District',
       products='White/refined sugar, molasses, ethanol, electricity (co-gen)',
       capacity_installed='8,500 TCD crushing; 180,000+ tpa sugar',
       capacity_utilised='~180,000 tpa — Uganda\'s largest sugar producer (~50% national output)',
       employees='12,500',
       est=1930, ownership='Madhvani Group (East African Holdings Ltd) — Uganda/Indian',
       exports='East Africa'),

  dict(name='Kinyara Sugar', chain='Sugar & Confectionery', lat=1.6830, lng=31.7170,
       loc='Kinyara, Masindi District',
       products='White sugar, molasses, electricity (co-gen)',
       capacity_installed='10,000 TCD crushing; ~110,000 tpa sugar',
       capacity_utilised='~110,000 tpa (31% national output)',
       employees='—',
       est=1964, ownership='Sarrai Group (formerly Rai Group, Kenya); GoU sold 70% by 2011',
       exports='East Africa'),

  dict(name='SCOUL — Sugar Corporation of Uganda', chain='Sugar & Confectionery', lat=0.3850, lng=32.9210,
       loc='Lugazi, Buikwe District',
       products='White sugar, molasses, co-generation electricity (30 MW)',
       capacity_installed='125,000 tpa',
       capacity_utilised='~60,000 tpa (17% national output)',
       employees='7,000',
       est=1924, ownership='Mehta Group — India/Uganda',
       exports='East Africa'),

  dict(name='Mayuge Sugar', chain='Sugar & Confectionery', lat=0.4580, lng=33.4840,
       loc='Mayuge District',
       products='Sugar, extra neutral alcohol (ENA), ethanol, electricity (9.2 MW co-gen)',
       capacity_installed='3,500 TCD; 60,000 tpa sugar; 30 KLPD distillery',
       capacity_utilised='~60,000 tpa',
       employees='~63 direct; outgrowers ecosystem',
       est=2009, ownership='MP Group of Industries — Uganda private',
       exports='East Africa'),

  dict(name='Hoima Sugar Ltd', chain='Sugar & Confectionery', lat=1.2525, lng=31.1933,
       loc='Kiswaza, Kikuube District',
       products='Sugar, molasses',
       capacity_installed='1,500 MT/day crushing',
       capacity_utilised='Operational',
       employees='2,000–5,000 (ramping)',
       est=2016, ownership='Sarrai Group (Rai Holdings) — Kenya/Uganda',
       exports='East Africa'),

  dict(name='GM Sugar Uganda Ltd', chain='Sugar & Confectionery', lat=0.4270, lng=33.1810,
       loc='Nakibizzi, Njeru, Buikwe District',
       products='White sugar, extra neutral alcohol/ethanol (8 m litres p.a.)',
       capacity_installed='~1,250 TCD initial; expanded',
       capacity_utilised='Operational',
       employees='—',
       est=2005, ownership='Private investors',
       exports='East Africa'),

  dict(name='Bugiri Sugar Factory (under construction)', chain='Sugar & Confectionery', lat=0.5700, lng=33.7420,
       loc='Bugubo Village, Bugiri District',
       products='Brown granular sugar',
       capacity_installed='240 MT/day; ~60,000 MT/year',
       capacity_utilised='Operational since ~2023',
       employees='—',
       est=2010, ownership='Private investors (acquired 2020)',
       exports='—'),

  dict(name='Busoga Sugar Processing Factory', chain='Sugar & Confectionery', lat=0.8241, lng=33.3325,
       loc='Luuka District',
       products='Brown sugar',
       capacity_installed='1,250 TCD',
       capacity_utilised='Construction delayed (UDC project)',
       employees='—',
       est=2020, ownership='Uganda Development Corporation (UDC) / Government of Uganda',
       exports='—'),

  dict(name='Victoria Sugar Ltd', chain='Sugar & Confectionery', lat=0.8330, lng=32.4740,
       loc='Luweero District',
       products='Brown granular sugar, bagasse electricity (16 MW)',
       capacity_installed='3,000 TCD crushing; ~36,000 tpa sugar',
       capacity_utilised='Commissioned Dec 2024; operational',
       employees='>8,000 direct',
       est=2018, ownership='Victoria Group of Companies — Ugandan private; USD 150 m investment',
       exports='East Africa'),

  dict(name='Tian Tang Group Ltd', chain='Sugar & Confectionery', lat=0.3070, lng=32.7820,
       loc='Kasenge/Mbalala, Mukono District',
       products='Sugar, confectionery; also steel, foam, plywood (diversified)',
       capacity_installed='—', capacity_utilised='Operational',
       employees='>1,500 across group',
       est=2015, ownership='Zhang Zhigang (Chinese entrepreneur) — 12 subsidiaries in Uganda',
       exports='East Africa'),

  dict(name='Ntake Bakery & Company Ltd', chain='Sugar & Confectionery', lat=0.2967, lng=32.5520,
       loc='Nalukolongo, Kampala',
       products='Bread, confectionery, wheat flour (300 MT/day twin mill), edible oil, soap, industrial fats',
       capacity_installed='300 MT/day twin wheat mill; 25 MT/day bakery',
       capacity_utilised='Operational across 5 production sites',
       employees='—',
       est=1978, ownership='Dr Canon Gaster Lule & Mrs Edith Lule family — Ugandan',
       exports='East Africa'),

  # ── Plastics & Packaging ──────────────────────────────────────────────────
  dict(name='Nice House of Plastics', chain='Plastics & Packaging', lat=0.3180, lng=32.7180,
       loc='Namanve Industrial Park, Kampala',
       products='Household and industrial plastics — containers, pipes, packaging, fittings',
       capacity_installed='—',
       capacity_utilised='Leading plastics manufacturer in Uganda',
       employees='—',
       est=1970, ownership='Dr James Mulwana family — Ugandan',
       exports='East Africa'),

  dict(name='Nile Plastic Industries', chain='Plastics & Packaging', lat=0.3150, lng=32.7110,
       loc='Kampala',
       products='Plastic bags, wrapping/packing film, nursery bags, shrink wrap',
       capacity_installed='—', capacity_utilised='Operational',
       employees='1–10',
       est=1992, ownership='Private Ugandan',
       exports='—'),

  dict(name='Quality Plastics', chain='Plastics & Packaging', lat=0.3530, lng=32.7520,
       loc='Mukono',
       products='Printed/plain industrial packaging, DPC sheets, PET preforms, blown PET bottles, PE film recycling',
       capacity_installed='—', capacity_utilised='Operational',
       employees='~71–74',
       est=1997, ownership='Rahim Shamsy (Director) — private',
       exports='East Africa'),

  dict(name='Luuka Plastics Ltd', chain='Plastics & Packaging', lat=0.3680, lng=32.5760,
       loc='Kawempe, Kampala (also Namanve & Matugga)',
       products='Flexible packaging films, PP films, printed packaging materials',
       capacity_installed='—', capacity_utilised='Operational across 3 plants',
       employees='—',
       est=2004, ownership='Badru Muwanga (Founder/Chairman) — Ugandan',
       exports='Kenya, Tanzania, Rwanda, Burundi, DRC, South Sudan'),

  dict(name='Acacia Plastics (Acacia Foundation Ltd)', chain='Plastics & Packaging', lat=0.4800, lng=32.6300,
       loc='Matugga, Wakiso District',
       products='PET bottles, plastic bottle recycling',
       capacity_installed='20 MT recycled plastics/day (Phase 1); 100 MT/day (Phase 2)',
       capacity_utilised='Phase 1 operational; Phase 2 expanding',
       employees='—',
       est=2021, ownership='Tony Nie Hao (Chinese founder); UGX 20 bn investment',
       exports='—'),

  dict(name='Victoria Nile Plastics Ltd', chain='Plastics & Packaging', lat=0.4290, lng=33.2010,
       loc='Jinja',
       products='Plastic products (injection moulded, blown)',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=0, ownership='Alpesh M Jiyani (Director) — Indian-origin private',
       exports='—'),

  dict(name='East African Packaging Solutions (EAPS)', chain='Plastics & Packaging', lat=0.4280, lng=33.1820,
       loc='Njeru Town, Jinja / Buikwe District',
       products='Corrugated cartons, pulp-moulded egg trays, 2-ply kraft paper',
       capacity_installed='3,600 MT boxes/month',
       capacity_utilised='ISO 9001 / 22000 / 45001 certified; operational',
       employees='—',
       est=0, ownership='Madhvani Group — Uganda/Indian',
       exports='East Africa'),

  dict(name='Fafa Glass Industries Ltd', chain='Plastics & Packaging', lat=1.0860, lng=34.1810,
       loc='Sino-Uganda Mbale Industrial Park',
       products='Float glass, aluminium products, glass panels',
       capacity_installed='—', capacity_utilised='Operational',
       employees='—',
       est=2020, ownership='Linked to Tian Tang Group (Chinese) — Sino-Uganda Mbale Industrial Park',
       exports='East Africa'),

  # ── Cement & Building Materials ───────────────────────────────────────────
  dict(name='Tororo Cement', chain='Cement & Building Materials', lat=0.6920, lng=34.1750,
       loc='Tororo',
       products='Portland cement, pozzolanic cement',
       capacity_installed='5,000,000 tpa installed',
       capacity_utilised='~3,000,000 tpa (60%); Uganda\'s largest cement producer',
       employees='~1,500 direct; 8,000 total ecosystem',
       est=1952, ownership='Brij Gagrani (Indian-origin private); privatised 1995',
       exports='East Africa'),

  dict(name='Hima Cement', chain='Cement & Building Materials', lat=0.3180, lng=30.1330,
       loc='Hima, Kasese District',
       products='Portland cement, blended cement',
       capacity_installed='~2,000,000 tpa total (Hima plant 850,000 tpa + Tororo/Namanve grinding)',
       capacity_utilised='Operational',
       employees='~320 permanent + 200 contractors',
       est=1994, ownership='Sarrai Group — acquired from LafargeHolcim Nov 2023/2024',
       exports='East Africa'),

  dict(name='Dura Limestone Quarry (Hima Cement)', chain='Cement & Building Materials', lat=0.1830, lng=30.4500,
       loc='Kamwenge District',
       products='Limestone (raw material for Hima Cement)',
       capacity_installed='450 ha lease; boosted Hima capacity from 350,000 to 850,000 tpa',
       capacity_utilised='Active mining (Quarry C); reserves to ~2036',
       employees='—',
       est=2008, ownership='Hima Cement Ltd (Sarrai Group) — mining lease from MoEMD',
       exports='—'),

  dict(name='Simba Cement', chain='Cement & Building Materials', lat=0.3220, lng=32.7170,
       loc='Namanve, Kampala',
       products='Portland cement (pozzolanic, OPC, Portland pozzolana)',
       capacity_installed='1,000,000 tpa',
       capacity_utilised='Operational',
       employees='~400',
       est=2018, ownership='National Cement Co. Ltd Kenya (Devki Group, 85%; IFC 15%); USD 185 m investment',
       exports='East Africa'),

  dict(name='Kampala Cement', chain='Cement & Building Materials', lat=0.3260, lng=32.7260,
       loc='Namanve, Kampala',
       products='Portland cement (pozzolanic, OPC, Portland pozzolana)',
       capacity_installed='~1,000,000 tpa',
       capacity_utilised='Operational',
       employees='~21',
       est=0, ownership='Multiple Industries Ltd — Uganda private',
       exports='East Africa'),

  dict(name='NE Uganda Clinker Plant (under construction)', chain='Cement & Building Materials', lat=2.5000, lng=34.0000,
       loc='Moroto, Karamoja — Northeast Uganda',
       products='Clinker and cement (Yaobai brand)',
       capacity_installed='Phase 1: 6,000 tpd clinker; Phase 2: 12,000 tpd',
       capacity_utilised='Phase 1 commissioned Apr 2026',
       employees='>1,533 projected',
       est=2023, ownership='Yaobai International / West China Cement Ltd (HK-listed); USD 300 m',
       exports='East Africa'),

  dict(name='Buikwe Clinker Plant — West International (under construction)', chain='Cement & Building Materials', lat=0.3520, lng=33.0030,
       loc='Njeru, Buikwe District',
       products='Cement grinding (3 Mtpa station; two 1.5 Mtpa units)',
       capacity_installed='3,000,000 tpa; USD 200 m investment',
       capacity_utilised='Under construction — target completion 2025',
       employees='1,800 projected',
       est=2023, ownership='West International Holdings Ltd (WIH) — Chinese-Ugandan JV',
       exports='Uganda, Tanzania, Kenya'),

  dict(name='Goodwill Uganda Ceramic Co. Ltd', chain='Cement & Building Materials', lat=0.8320, lng=32.0820,
       loc='Liao Shen Industrial Park, Kapeeka, Nakaseke District',
       products='Ceramic wall and floor tiles (200+ designs)',
       capacity_installed='40,000 m²/day',
       capacity_utilised='Operational since Apr 2018; 40% exported',
       employees='1,150 Ugandans + 60 Chinese technicians',
       est=2017, ownership='Chinese-founded; USD 30 m investment; Liao Shen Industrial Park',
       exports='East Africa (40% of output)'),

  dict(name='Hua Hui International Ltd', chain='Cement & Building Materials', lat=0.8340, lng=32.0840,
       loc='Liao Shen Industrial Park, Kapeeka, Nakaseke District',
       products='Ceramic tiles (two production lines)',
       capacity_installed='~40,000 m²/day (shared park infrastructure)',
       capacity_utilised='Operational',
       employees='—',
       est=2018, ownership='Chinese-owned — Liao Shen Industrial Park, Kapeeka',
       exports='East Africa (~40% export)'),
]

def esc(s):
    """Escape for a JS single-quoted string value."""
    return (str(s)
            .replace('\\', '\\\\')
            .replace("'", "\\'")
            .replace('`', '\\`')
            .replace('${', '\\${'))

def factory_js(f):
    est = f['est'] if f['est'] != 0 else '—'
    lines = [
        f"  {{name:'{esc(f['name'])}',chain:'{esc(f['chain'])}',lat:{f['lat']},lng:{f['lng']},",
        f"   loc:'{esc(f['loc'])}',",
        f"   products:'{esc(f['products'])}',",
        f"   capacity_installed:'{esc(f['capacity_installed'])}',",
        f"   capacity_utilised:'{esc(f['capacity_utilised'])}',",
        f"   employees:'{esc(f['employees'])}',",
        f"   est:'{est}',",
        f"   ownership:'{esc(f['ownership'])}',",
        f"   exports:'{esc(f['exports'])}'}},",
    ]
    return '\n'.join(lines)

# Build the JS block grouped by chain
chain_order = [
    'Iron & Steel', 'Copper & Allied Metals', 'Automotive',
    'Textiles & Garments', 'Pharmaceuticals', 'Petrochemicals & Fertilizers',
    'Sugar & Confectionery', 'Plastics & Packaging', 'Cement & Building Materials',
]
current_chain = None
js_entries = []
for f in FACTORIES:
    if f['chain'] != current_chain:
        current_chain = f['chain']
        js_entries.append(f'  // ── {current_chain} ──')
    js_entries.append(factory_js(f))

factories_js = 'const FACTORIES=[\n' + '\n'.join(js_entries).rstrip(',') + '\n];'

# ── Updated popup template ────────────────────────────────────────────────────
NEW_POPUP = r""".bindPopup(
        `<div style="min-width:260px;max-width:320px;font-family:Segoe UI,system-ui,sans-serif">
          <div style="font-weight:700;font-size:13px;color:${col};margin-bottom:2px">${f.name}</div>
          <div style="font-size:11px;color:#666;margin-bottom:1px">${f.chain}</div>
          <div style="font-size:11px;color:#555;margin-bottom:6px">📍 ${f.loc}</div>
          <hr style="margin:4px 0;border:none;border-top:1px solid #e8e8e8">
          <table style="font-size:11px;width:100%;border-collapse:collapse;line-height:1.5">
            <tr><td colspan="2" style="padding:3px 0;color:#333;font-style:italic">${f.products}</td></tr>
            ${f.capacity_installed!=='—'?`<tr><td style="color:#888;padding:2px 8px 2px 0;white-space:nowrap;vertical-align:top;width:42%">Installed cap.</td><td style="color:#222;padding:2px 0">${f.capacity_installed}</td></tr>`:''}
            ${f.capacity_utilised!=='—'?`<tr><td style="color:#888;padding:2px 8px 2px 0;white-space:nowrap;vertical-align:top">Current output</td><td style="color:#222;padding:2px 0">${f.capacity_utilised}</td></tr>`:''}
            ${f.employees!=='—'?`<tr><td style="color:#888;padding:2px 8px 2px 0;white-space:nowrap;vertical-align:top">Employees</td><td style="color:#222;padding:2px 0">${f.employees}</td></tr>`:''}
            ${f.est!=='—'?`<tr><td style="color:#888;padding:2px 8px 2px 0;white-space:nowrap;vertical-align:top">Established</td><td style="color:#222;padding:2px 0">${f.est}</td></tr>`:''}
            ${f.ownership!=='—'?`<tr><td style="color:#888;padding:2px 8px 2px 0;white-space:nowrap;vertical-align:top">Ownership</td><td style="color:#222;padding:2px 0">${f.ownership}</td></tr>`:''}
            ${f.exports!=='—'?`<tr><td style="color:#888;padding:2px 8px 2px 0;white-space:nowrap;vertical-align:top">Exports</td><td style="color:#222;padding:2px 0">${f.exports}</td></tr>`:''}
          </table>
        </div>`)"""

# ── Patch HTML ────────────────────────────────────────────────────────────────
html = HTML.read_text(encoding='utf-8')

# Replace FACTORIES array
old_start = html.index('const FACTORIES=[')
old_end   = html.index('];', old_start) + 2
html = html[:old_start] + factories_js + html[old_end:]
print(f'FACTORIES replaced ({len(FACTORIES)} entries)')

# Replace popup template
old_popup_start = html.index('.bindPopup(\n        `<div style="min-width:')
old_popup_end   = html.index('`)', old_popup_start) + 2
html = html[:old_popup_start] + NEW_POPUP + html[old_popup_end:]
print('Popup template updated')

HTML.write_text(html, encoding='utf-8')
print(f'Written: {HTML} ({HTML.stat().st_size//1024} KB)')
